export {default as authReducer} from './authSlice'
export {default as playerCateguryReducer} from './playerCategurySlice'
export {default as playerReducer} from './playerSlice'
export {default as teamReducer} from './teamSlice'
export {default as modelReducer} from './modelSlice'
export {default as userReducer} from './userSlice'
export {default as soldPlayerReducer} from './soldPlayerSlice'